# The URL the site will be built for
base_url = "https://niikunihiro.github.io"

description = "\"Niiko はその時思った...\""

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "inspired-github"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The site theme to use.
theme = "ergo"

title = "Niiko thought at that time"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Specify a profile picture to use for the logos in the theme. It can be svg, png, jpg, whatever, just make sure to copy the logo you want and put it in img/${YOUR_PROFILE}.*
# and update your config.toml accordingly
profile = "profile.jpg"
color_themes = ["default", "dark"]
country_flags = true # Display languages as country flags. Defaults to false.

[[extra.socials]]
icon = "github"
display = "niikunihiro"
uri = "https://github.com/niikunihiro"

[extra.font_awesome]
kit = "e307e34624"
